// <auto-generated />
using System;
using MetaEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetaEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetaEngineDbContext))]
    [Migration("20260715071756_AddIdentityAndWorkspaceSecurity")]
    partial class AddIdentityAndWorkspaceSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetaEngine.Domain.Model.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_events_user_id");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_workspace_id_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.CalculationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("engine_version");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<double?>("FinalAccum")
                        .HasColumnType("double precision")
                        .HasColumnName("final_accum");

                    b.Property<double?>("HighWaterMark")
                        .HasColumnType("double precision")
                        .HasColumnName("high_water_mark");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("input_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<double?>("MaxDrawdown")
                        .HasColumnType("double precision")
                        .HasColumnName("max_drawdown");

                    b.Property<string>("MissingDataRule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("missing_data_rule");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StrategyParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("strategy_parameters_json");

                    b.Property<int?>("StrategySchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("strategy_schema_version");

                    b.Property<string>("StrategyType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_type");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("timeframe");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_calculation_runs");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_calculation_runs_created_by_user_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_calculation_runs_portfolio_id");

                    b.HasIndex("PresetId")
                        .HasDatabaseName("ix_calculation_runs_preset_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_calculation_runs_status_created_at");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_calculation_runs_workspace_id_created_at");

                    b.ToTable("calculation_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_calculation_runs_counts", "point_count >= 0 AND trade_count >= 0");

                            t.HasCheckConstraint("ck_calculation_runs_input", "(input_type = 'Portfolio' AND portfolio_id IS NOT NULL AND preset_id IS NULL) OR (input_type = 'Preset' AND preset_id IS NOT NULL AND portfolio_id IS NULL)");

                            t.HasCheckConstraint("ck_calculation_runs_period", "period_end >= period_start");

                            t.HasCheckConstraint("ck_calculation_runs_strategy", "(kind = 'Base' AND strategy_type IS NULL AND strategy_schema_version IS NULL AND strategy_parameters_json IS NULL) OR (kind = 'Strategy' AND strategy_type IS NOT NULL AND strategy_schema_version IS NOT NULL AND strategy_parameters_json IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.OptimizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("engine_version");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("input_type");

                    b.Property<string>("MissingDataRule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("missing_data_rule");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<long>("ProcessedCandidates")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_candidates");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("sample_count");

                    b.Property<string>("SearchSpaceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("search_space_json");

                    b.Property<int>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StopRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stop_requested_at");

                    b.Property<int>("StrategySchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("strategy_schema_version");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_type");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("timeframe");

                    b.Property<int>("TopCount")
                        .HasColumnType("integer")
                        .HasColumnName("top_count");

                    b.Property<long?>("TotalCandidates")
                        .HasColumnType("bigint")
                        .HasColumnName("total_candidates");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_optimization_jobs");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_optimization_jobs_created_by_user_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_optimization_jobs_portfolio_id");

                    b.HasIndex("PresetId")
                        .HasDatabaseName("ix_optimization_jobs_preset_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_optimization_jobs_status_created_at");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_optimization_jobs_workspace_id_created_at");

                    b.ToTable("optimization_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_optimization_jobs_input", "(input_type = 'Portfolio' AND portfolio_id IS NOT NULL AND preset_id IS NULL) OR (input_type = 'Preset' AND preset_id IS NOT NULL AND portfolio_id IS NULL)");

                            t.HasCheckConstraint("ck_optimization_jobs_period", "period_end >= period_start");

                            t.HasCheckConstraint("ck_optimization_jobs_progress", "processed_candidates >= 0 AND (total_candidates IS NULL OR total_candidates >= processed_candidates)");

                            t.HasCheckConstraint("ck_optimization_jobs_sample_count", "sample_count > 0");

                            t.HasCheckConstraint("ck_optimization_jobs_schema_version", "strategy_schema_version > 0");

                            t.HasCheckConstraint("ck_optimization_jobs_seed", "seed >= 0");

                            t.HasCheckConstraint("ck_optimization_jobs_top_count", "top_count > 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.OptimizationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AverageAccum")
                        .HasColumnType("double precision")
                        .HasColumnName("average_accum");

                    b.Property<double>("CompoundedAccum")
                        .HasColumnType("double precision")
                        .HasColumnName("compounded_accum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OptimizationJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimization_job_id");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<int>("ProfitableSampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("profitable_sample_count");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("SampleMetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_metrics_json");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<double>("WorstAccum")
                        .HasColumnType("double precision")
                        .HasColumnName("worst_accum");

                    b.Property<double>("WorstMaxDrawdown")
                        .HasColumnType("double precision")
                        .HasColumnName("worst_max_drawdown");

                    b.HasKey("Id")
                        .HasName("pk_optimization_results");

                    b.HasIndex("OptimizationJobId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_optimization_results_optimization_job_id_rank");

                    b.ToTable("optimization_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_optimization_results_counts", "trade_count >= 0 AND profitable_sample_count >= 0");

                            t.HasCheckConstraint("ck_optimization_results_rank", "rank > 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PortfolioPoint", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Diff")
                        .HasColumnType("double precision")
                        .HasColumnName("diff");

                    b.HasKey("PortfolioId", "Timestamp")
                        .HasName("pk_portfolio_points");

                    b.ToTable("portfolio_points", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PortfolioVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalization_version");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.Property<Guid>("PortfolioKey")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_key");

                    b.Property<string>("SeriesChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("series_checksum");

                    b.Property<string>("SourceChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_checksum");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("timeframe");

                    b.Property<string>("ValueScale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("value_scale");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("value_type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_portfolios_created_by_user_id");

                    b.HasIndex("WorkspaceId", "PortfolioKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolios_workspace_id_portfolio_key_version");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_point_count", "point_count >= 0");

                            t.HasCheckConstraint("ck_portfolios_version", "version > 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PresetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_preset_items");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_preset_items_portfolio_id");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("ix_preset_items_strategy_id");

                    b.HasIndex("PresetId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_preset_items_preset_id_sort_order");

                    b.ToTable("preset_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_preset_items_period", "ends_at IS NULL OR ends_at >= starts_at");

                            t.HasCheckConstraint("ck_preset_items_source", "(source_type = 'Portfolio' AND portfolio_id IS NOT NULL AND strategy_id IS NULL) OR (source_type = 'Strategy' AND strategy_id IS NOT NULL AND portfolio_id IS NULL)");

                            t.HasCheckConstraint("ck_preset_items_weight", "weight >= 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PresetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PresetKey")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_presets");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_presets_created_by_user_id");

                    b.HasIndex("WorkspaceId", "PresetKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_presets_workspace_id_preset_key_version");

                    b.ToTable("presets", null, t =>
                        {
                            t.HasCheckConstraint("ck_presets_version", "version > 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.RunArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalculationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculation_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.Property<string>("SeriesChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("series_checksum");

                    b.HasKey("Id")
                        .HasName("pk_run_artifacts");

                    b.HasIndex("CalculationRunId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_run_artifacts_calculation_run_id_kind");

                    b.ToTable("run_artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_run_artifacts_point_count", "point_count >= 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.RunArtifactPoint", b =>
                {
                    b.Property<Guid>("RunArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_artifact_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Diff")
                        .HasColumnType("double precision")
                        .HasColumnName("diff");

                    b.HasKey("RunArtifactId", "Timestamp")
                        .HasName("pk_run_artifact_points");

                    b.ToTable("run_artifact_points", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.SavedStrategyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OptimizationResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimization_result_id");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<Guid>("ResultArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_artifact_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid?>("SourcePortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_portfolio_id");

                    b.Property<Guid?>("SourcePresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_preset_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("StrategyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_key");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_strategies");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_strategies_created_by_user_id");

                    b.HasIndex("OptimizationResultId")
                        .HasDatabaseName("ix_strategies_optimization_result_id");

                    b.HasIndex("ResultArtifactId")
                        .IsUnique()
                        .HasDatabaseName("ix_strategies_result_artifact_id");

                    b.HasIndex("SourcePortfolioId")
                        .HasDatabaseName("ix_strategies_source_portfolio_id");

                    b.HasIndex("SourcePresetId")
                        .HasDatabaseName("ix_strategies_source_preset_id");

                    b.HasIndex("WorkspaceId", "StrategyKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_strategies_workspace_id_strategy_key_version");

                    b.ToTable("strategies", null, t =>
                        {
                            t.HasCheckConstraint("ck_strategies_schema_version", "schema_version > 0");

                            t.HasCheckConstraint("ck_strategies_source", "(source_type = 'Portfolio' AND source_portfolio_id IS NOT NULL AND source_preset_id IS NULL) OR (source_type = 'Preset' AND source_preset_id IS NOT NULL AND source_portfolio_id IS NULL)");

                            t.HasCheckConstraint("ck_strategies_version", "version > 0");
                        });
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Infrastructure.Identity.IdentityAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user_credentials");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.AuditEvent", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_events_user_accounts_user_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.CalculationRun", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calculation_runs_user_accounts_created_by_user_id");

                    b.HasOne("MetaEngine.Domain.Model.PortfolioVersion", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calculation_runs_portfolios_portfolio_id");

                    b.HasOne("MetaEngine.Domain.Model.PresetVersion", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calculation_runs_presets_preset_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_runs_workspaces_workspace_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Portfolio");

                    b.Navigation("Preset");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.OptimizationJob", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_optimization_jobs_user_accounts_created_by_user_id");

                    b.HasOne("MetaEngine.Domain.Model.PortfolioVersion", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_optimization_jobs_portfolios_portfolio_id");

                    b.HasOne("MetaEngine.Domain.Model.PresetVersion", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_optimization_jobs_presets_preset_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_optimization_jobs_workspaces_workspace_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Portfolio");

                    b.Navigation("Preset");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.OptimizationResult", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.OptimizationJob", "OptimizationJob")
                        .WithMany("Results")
                        .HasForeignKey("OptimizationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_optimization_results_optimization_jobs_optimization_job_id");

                    b.Navigation("OptimizationJob");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PortfolioPoint", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.PortfolioVersion", "Portfolio")
                        .WithMany("Points")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_points_portfolios_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PortfolioVersion", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_portfolios_user_accounts_created_by_user_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_workspaces_workspace_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PresetItem", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.PortfolioVersion", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_preset_items_portfolios_portfolio_id");

                    b.HasOne("MetaEngine.Domain.Model.PresetVersion", "Preset")
                        .WithMany("Items")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preset_items_presets_preset_id");

                    b.HasOne("MetaEngine.Domain.Model.SavedStrategyVersion", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_preset_items_strategies_strategy_id");

                    b.Navigation("Portfolio");

                    b.Navigation("Preset");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PresetVersion", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_presets_user_accounts_created_by_user_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_presets_workspaces_workspace_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.RunArtifact", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.CalculationRun", "CalculationRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("CalculationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_artifacts_calculation_runs_calculation_run_id");

                    b.Navigation("CalculationRun");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.RunArtifactPoint", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.RunArtifact", "RunArtifact")
                        .WithMany("Points")
                        .HasForeignKey("RunArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_artifact_points_run_artifacts_run_artifact_id");

                    b.Navigation("RunArtifact");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.SavedStrategyVersion", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_strategies_user_accounts_created_by_user_id");

                    b.HasOne("MetaEngine.Domain.Model.OptimizationResult", "OptimizationResult")
                        .WithMany()
                        .HasForeignKey("OptimizationResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_strategies_optimization_results_optimization_result_id");

                    b.HasOne("MetaEngine.Domain.Model.RunArtifact", "ResultArtifact")
                        .WithOne()
                        .HasForeignKey("MetaEngine.Domain.Model.SavedStrategyVersion", "ResultArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_strategies_run_artifacts_result_artifact_id");

                    b.HasOne("MetaEngine.Domain.Model.PortfolioVersion", "SourcePortfolio")
                        .WithMany()
                        .HasForeignKey("SourcePortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_strategies_portfolios_source_portfolio_id");

                    b.HasOne("MetaEngine.Domain.Model.PresetVersion", "SourcePreset")
                        .WithMany()
                        .HasForeignKey("SourcePresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_strategies_presets_source_preset_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_strategies_workspaces_workspace_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("OptimizationResult");

                    b.Navigation("ResultArtifact");

                    b.Navigation("SourcePortfolio");

                    b.Navigation("SourcePreset");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.WorkspaceMember", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_user_accounts_user_id");

                    b.HasOne("MetaEngine.Domain.Model.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MetaEngine.Infrastructure.Identity.IdentityAccount", b =>
                {
                    b.HasOne("MetaEngine.Domain.Model.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("MetaEngine.Infrastructure.Identity.IdentityAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_user_accounts_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MetaEngine.Infrastructure.Identity.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_user_credentials_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MetaEngine.Infrastructure.Identity.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_user_credentials_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MetaEngine.Infrastructure.Identity.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_user_credentials_user_id");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.CalculationRun", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.OptimizationJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PortfolioVersion", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.PresetVersion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.RunArtifact", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.UserAccount", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("MetaEngine.Domain.Model.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
